#! /usr/bin/python3

import os

print('Content-Type: text/html')
print('Status: 200 OK')
print()

print('''
<html>
<head> <title> Path info test </title></head>
<body>


''')

environ = os.environ
if 'PATH_INFO' in environ:
    print("These are the files in the cgi script path info:")
    print(environ['PATH_INFO'])
else:
    print('No results in cgi script\'s path info')

print('''
</body>
</html>

''')
